import type { Language } from './types'

export const translations = {
  uk: { today: 'Сьогодні', week: 'Тиждень', settings: 'Налаштування', month: 'Місяць', quarter: 'Квартал', year: 'Рік', change: 'Змінити', editPrice: 'Змінити ціну', show: 'Показати', hide: 'Приховати', save: 'Зберегти', reduction: 'Режим скорочення', goal: 'Денна ціль, шт.', achievements: 'Досягнення', language: 'Мова', safari: 'Додати SmokeLog на iPhone', safariText: 'У Safari натисни «Поділитися», потім «На початковий екран». Назву можна змінити перед додаванням.', dismiss: 'Більше не показувати', observed: 'Факт за 7 днів', projected: 'Прогноз за темпом', underGoal: 'Днів у межах цілі', longestPause: 'Найдовша пауза', returned: 'Повернуто часу', saved: 'Орієнтовно збережено' },
  ru: { today: 'Сегодня', week: 'Неделя', settings: 'Настройки', month: 'Месяц', quarter: 'Квартал', year: 'Год', change: 'Изменить', editPrice: 'Изменить цену', show: 'Показать', hide: 'Скрыть', save: 'Сохранить', reduction: 'Режим сокращения', goal: 'Дневная цель, шт.', achievements: 'Достижения', language: 'Язык', safari: 'Добавить SmokeLog на iPhone', safariText: 'В Safari нажми «Поделиться», затем «На экран Домой». Название можно изменить перед добавлением.', dismiss: 'Больше не показывать', observed: 'Факт за 7 дней', projected: 'Прогноз по темпу', underGoal: 'Дней в пределах цели', longestPause: 'Самая длинная пауза', returned: 'Возвращено времени', saved: 'Ориентировочно сэкономлено' },
  en: { today: 'Today', week: 'Week', settings: 'Settings', month: 'Month', quarter: 'Quarter', year: 'Year', change: 'Edit', editPrice: 'Change price', show: 'Show', hide: 'Hide', save: 'Save', reduction: 'Reduction mode', goal: 'Daily goal, units', achievements: 'Achievements', language: 'Language', safari: 'Add SmokeLog to iPhone', safariText: 'In Safari tap Share, then Add to Home Screen. You can edit the app name before adding it.', dismiss: 'Do not show again', observed: 'Observed over 7 days', projected: 'Projected at this pace', underGoal: 'Days within goal', longestPause: 'Longest pause', returned: 'Time returned', saved: 'Estimated saved' },
} as const

export type TranslationKey = keyof typeof translations.uk
export function t(language: Language, key: TranslationKey): string { return translations[language][key] }
